name: Build/release

on:
  push:
    tags:
      - v**
    branches:
      - develop

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@master
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.14.0
      - name: Clean cache
        run: |
            npm cache clean -force
      - name: Prepare for app notarization (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.API_KEY_ID }}.p8
      - name: Pre npm install
        run: npm install
      - name: Build/release Electron app
        uses: Yan-Jobs/action-electron-builder@v1.7.0
        with:
          github_token: ${{ secrets.github_token }}
          mac_certs: ${{ secrets.MAC_CERT }}
          mac_certs_password: ${{ secrets.MAC_CERT_PWD }}
          windows_certs: ${{ secrets.WIN_CERT }}
          windows_certs_password: ${{ secrets.WIN_CERT_PWD }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: build:ci
          max_attempts: 3
        env:
          appleId: ${{ secrets.APPLE_ID }}
          appleIdPassword: ${{ secrets.APPLE_ID_PWD }},
          API_KEY_ID: ${{ secrets.API_KEY_ID }},
          API_KEY_ISSUER_ID: ${{ secrets.API_KEY_ISSUER_ID }}
          NODE_OPTIONS: '--max_old_space_size=4096'